export const LOG_TYPES = {
  login: '用户登录',
  register: '用户注册',
  create_teacher: '创建教师',
  update_teacher: '更新教师信息',
  delete_teacher: '删除教师',
  create_class: '创建班级',
  update_class: '更新班级',
  update_student: '更新学生信息',
  update_profile: '更新个人信息',
  update_password: '修改密码',
  update_settings: '更新系统设置',
  view_scores: '查看成绩',
  download_template: '下载模板',
  import_teachers: '导入教师',
  import_students: '导入学生',
  reset_password: '重置密码',
  student_report: '学生报到',
  delete_student: '删除学生',
  system_auto: '系统自动操作',
  create_building: '创建宿舍楼',
  create_room: '创建宿舍房间',
  update_room: '更新宿舍房间',
  delete_room: '删除宿舍房间',
  checkout: '退宿',
  change_room: '调整宿舍',
  assign_room: '分配宿舍',
  analyze_class_scores: '分析班级成绩',
  assign_students: '分配学生',
  remove_students: '移除学生',
  assign_dormitories: '分配宿舍',
  delete_building:'删除宿舍楼',
  update_building:'更新宿舍楼',
  create_todo:'创建待办事项',
  update_todo:'更新待办事项',
  delete_todo:'删除待办事项',
  update_student_report_status:'更新学生报到状态',
  generate_analysis_report:'生成分析报告',

}

export type LogType = keyof typeof LOG_TYPES
